### ISSUE TITLE
Add auth0 example on separate branch

### ISSUE THREAD

**Issue by smaccoun** [smaccoun/elm-haskell-scaffold#5]

**Comment by sigrlami** [comment]
@smaccoun I have my own library for Auth0. In general, service provides many options. Which one do you need - email, passwordless, sms-based?

**Comment by jetaggart** [comment]
I'd go with just email/password to start so it's most accessible.

**Comment by sigrlami** [comment]
@jetaggart noted, will do setup over weekend
